# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, '12.0'

target 'NearByApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearByApp
  pod 'Kingfisher', '~> 7.0'

  target 'NearByAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearByAppUITests' do
    # Pods for testing
  end

end
